export interface SeedQuestion {
  title: string;
  company: string | null;
  genre: string;
  difficulty: string;
  description: string;
  hints: string[];
  modelAnswer: string;
}

export const SEED_QUESTIONS: SeedQuestion[] = [
  {
    title: "Design the Twitter feed",
    company: "Twitter",
    genre: "feed",
    difficulty: "hard",
    description: "Design a system that allows users to post tweets and see a personalized feed of tweets from people they follow. The system must support 300M daily active users, with reads heavily outnumbering writes.",
    hints: [
      "Consider fanout-on-write vs fanout-on-read for feed generation",
      "How do you handle celebrity accounts with millions of followers?",
      "What does the data model for tweets and follow relationships look like?",
      "How would you handle timeline cache invalidation?",
    ],
    modelAnswer: "Use a hybrid fanout approach: fanout-on-write for regular users (push tweets to follower timelines at write time), fanout-on-read for celebrities (pull on demand). Store timelines in Redis sorted sets (tweet IDs by timestamp). Tweets in Cassandra (wide-column, write-optimized). Follow graph in a graph DB or adjacency list in Redis. CDN for media. Load balancers → stateless app servers. Separate read/write paths. Timeline service, tweet service, user service as independent microservices. For 300M DAU: estimate ~100M feed reads/day → Redis cluster with ~1M timeline entries cached per shard.",
  },
  {
    title: "Design Uber's dispatch system",
    company: "Uber",
    genre: "distributed-systems",
    difficulty: "hard",
    description: "Design the backend system that matches riders with nearby drivers in real time. The system must handle 15M trips per day globally, with sub-second matching latency.",
    hints: [
      "How do you efficiently find nearby drivers without querying all drivers?",
      "What happens if the matching service goes down mid-ride?",
      "How do you handle surge pricing decisions?",
      "Consider geospatial indexing strategies.",
    ],
    modelAnswer: "Geospatial index using geohash or S2 cells — drivers report location every 4 seconds to a location service, stored in Redis geospatial index. Matching service queries drivers within expanding radius using GEORADIUS. WebSocket or long-polling for real-time driver updates to rider app. Ride state machine (requested → matching → accepted → in-progress → completed) persisted in Postgres with Redis cache. Kafka for async events (trip completion → billing → ratings). Separate supply/demand forecasting service for surge. Distributed lock (Redis) on driver assignment to prevent double-booking. Fallback: if matching service fails, client retries with exponential backoff.",
  },
  {
    title: "Design Netflix's CDN",
    company: "Netflix",
    genre: "cdn",
    difficulty: "hard",
    description: "Design the content delivery system that streams video to 200M subscribers globally with minimal buffering. Netflix accounts for ~15% of global internet traffic.",
    hints: [
      "How do you decide which content to pre-position at which edge nodes?",
      "What encoding formats and bitrates do you store?",
      "How does the client adapt to changing network conditions?",
      "How do you handle a new popular show that everyone watches at once?",
    ],
    modelAnswer: "Open Connect CDN: Netflix-operated servers at ISP data centers. Pre-position popular content using ML predictions (top 1000 titles cover ~80% of streams). Store multiple encodings (H.264/H.265/AV1) at 7 bitrates (0.5Mbps → 20Mbps). Client uses ABR (adaptive bitrate) — downloads 2-4 second chunks, switches quality based on buffer health and bandwidth estimate. Manifest file served from AWS; actual chunks from nearest Open Connect appliance. For new popular shows: replicate to all edge nodes before launch. CDN miss → origin in AWS S3. ISP peering reduces transit cost. Separate metadata service (title, thumbnails) from video delivery path.",
  },
  {
    title: "Design WhatsApp messaging",
    company: "WhatsApp",
    genre: "messaging",
    difficulty: "medium",
    description: "Design a messaging system that supports 1:1 and group chats, delivery receipts, and end-to-end encryption for 2B users. Messages must be delivered even when recipients are offline.",
    hints: [
      "How do you handle message delivery when the recipient is offline?",
      "What is the data model for group chats with up to 1024 members?",
      "How do delivery receipts (sent/delivered/read) work at scale?",
      "Where do you store message history?",
    ],
    modelAnswer: "Persistent WebSocket connections from clients to chat servers. Message queue (Kafka) for reliable delivery — messages persisted until ACKed. When recipient offline: store in DB, push notification via APNS/FCM, deliver on reconnect. Message store: Cassandra with (chat_id, timestamp) partition key for efficient range queries. E2E encryption: Signal Protocol — keys never on server. Group messages: fan out to each member's queue. Delivery receipts: client sends ACK → server updates status → notifies sender. Media stored in distributed blob store (separate from message store). Chat servers stateless behind load balancer; consistent hashing for WebSocket routing.",
  },
  {
    title: "Design Amazon's product search",
    company: "Amazon",
    genre: "search",
    difficulty: "medium",
    description: "Design a product search system that handles 500M product catalog entries and serves 1B search queries per day with sub-100ms latency. Results must be ranked by relevance and personalized.",
    hints: [
      "How do you index 500M products for full-text search?",
      "What signals go into ranking: relevance, sales, reviews, personalization?",
      "How do you handle search suggestions and spell correction?",
      "How do you update the index when product data changes?",
    ],
    modelAnswer: "Elasticsearch cluster for full-text search — inverted index on title, description, category. Separate ranking service: base score (BM25 relevance) × sales velocity × review score × personalization multiplier. Personalization: user's purchase/click history → feature vector → dot product with item embeddings (ANN index, e.g. FAISS). Query pipeline: spell check (edit distance) → query expansion (synonyms) → retrieval → rerank → filter by availability/price. Index updates: product change events → Kafka → index worker → Elasticsearch. Search suggestions: trie or prefix index in Redis. A/B test ranking changes continuously. Cache popular queries (Redis, TTL 5min).",
  },
  {
    title: "Design Google Docs collaborative editing",
    company: "Google",
    genre: "storage",
    difficulty: "hard",
    description: "Design a real-time collaborative document editor where multiple users can edit the same document simultaneously and see each other's changes instantly.",
    hints: [
      "How do you handle two users editing the same character position simultaneously?",
      "How do you sync state when a user reconnects after being offline?",
      "What is the data model for document content and edit history?",
      "How do you scale to millions of concurrent documents?",
    ],
    modelAnswer: "Operational Transformation (OT) or CRDT for conflict resolution — OT is simpler for server-mediated systems. Each operation (insert/delete at position) transformed against concurrent ops before applying. Server as source of truth: client sends op → server transforms against pending ops → broadcasts transformed op to all collaborators. Document stored as op log (append-only) + periodic snapshots in Bigtable. Presence (cursor positions) via separate lightweight pub/sub (Redis). WebSocket per document session; stateful collaboration server per active document. On reconnect: client sends last known revision → server replays missing ops. Separate read path (view document) from edit path. Autosave every 30s to prevent data loss.",
  },
  {
    title: "Design Airbnb's booking system",
    company: "Airbnb",
    genre: "payments",
    difficulty: "medium",
    description: "Design a booking platform that allows hosts to list properties and guests to search, book, and pay. The system must prevent double-bookings and handle payment processing reliably.",
    hints: [
      "How do you prevent two guests from booking the same property on the same night?",
      "How do you handle partial payment failures?",
      "What is the data model for availability calendars?",
      "How do you handle the search for available properties by date range?",
    ],
    modelAnswer: "Availability stored as date-range records per listing (not one record per day). Search uses availability index (Elasticsearch with date range filter). Booking flow: optimistic lock — reserve availability (status: HOLD with TTL 10min) → process payment → confirm booking atomically. Two-phase: if payment fails, release hold. Idempotency keys on payment API to prevent duplicate charges. Postgres for bookings/payments (ACID). Availability calendar: cache in Redis, invalidated on booking. Host payout via background job after check-in + grace period. Cancellation policy applied at booking service layer. Separate listing service, booking service, payment service — saga pattern for cross-service consistency.",
  },
  {
    title: "Design LinkedIn's news feed",
    company: "LinkedIn",
    genre: "feed",
    difficulty: "medium",
    description: "Design a professional news feed that shows posts from a user's connections and followed companies. Feed must be relevant, real-time, and personalized for 800M users.",
    hints: [
      "How is the LinkedIn feed different from Twitter's in terms of graph structure?",
      "How do you balance recency vs. relevance in ranking?",
      "How do you handle viral content that suddenly gets many engagements?",
    ],
    modelAnswer: "Push-pull hybrid similar to Twitter but with connection graph instead of follow graph. Connection degree matters (1st degree > 2nd degree). Feed generation: fanout-on-write for regular users, fanout-on-read for viral posts. Ranking model: engagement score × recency decay × connection strength × content type preference (ML model). Feed stored in Redis per user. Post engagement (likes, comments, shares) updates ranking score asynchronously via Kafka. Viral detection: if post engagement rate exceeds threshold, switch to pull-based for that post. Notification service for real-time feed updates. Separate professional content signals: job changes, endorsements, articles weighted higher.",
  },
  {
    title: "Design Dropbox file sync",
    company: "Dropbox",
    genre: "storage",
    difficulty: "medium",
    description: "Design a file synchronization service that keeps files in sync across multiple devices for 700M users. Files range from 1KB to 50GB.",
    hints: [
      "How do you efficiently sync only the changed parts of a file?",
      "How do you handle conflicts when the same file is edited on two devices simultaneously?",
      "Where do you store file metadata vs. file content?",
      "How do you handle large file uploads reliably?",
    ],
    modelAnswer: "Split files into 4MB chunks, hash each chunk (SHA-256). On sync: compare chunk hashes, upload only changed chunks (delta sync). Metadata (file path, chunk list, version) in Postgres. Chunks in S3 (content-addressed by hash — deduplication is free). Upload: multipart upload directly to S3 via presigned URLs. Client syncs via long-polling or WebSocket to notification service. Conflict: both versions kept, user prompted to resolve. Version history: immutable chunk store + metadata snapshots. Large file handling: chunked upload with resumable sessions. Bandwidth optimization: compress before upload, LAN sync (detect peers on same network).",
  },
  {
    title: "Design Slack real-time messaging",
    company: "Slack",
    genre: "messaging",
    difficulty: "hard",
    description: "Design a team messaging platform with channels, direct messages, search, and real-time notifications for 20M daily active users across thousands of workspaces.",
    hints: [
      "How do you isolate data between different company workspaces?",
      "How does channel message search work at scale?",
      "How do you deliver real-time messages to users who may be on web, desktop, and mobile?",
    ],
    modelAnswer: "Workspace-level data isolation — each workspace can be sharded independently. Messages stored in Cassandra (workspace_id, channel_id, timestamp). Full-text search via Elasticsearch per workspace index. Real-time delivery: WebSocket gateway (stateful) → client. When user sends message: API server → Kafka → fanout service → pushes to all channel members' WebSocket connections. Members not connected: push notification. Presence service: Redis tracking connected users per workspace. Read state tracking: last-read timestamp per user per channel in Redis. App unfurling (link previews) as async job. Audit logs for enterprise customers. Rate limiting per workspace to prevent noisy neighbors.",
  },
  {
    title: "Design YouTube's video upload pipeline",
    company: "YouTube",
    genre: "cdn",
    difficulty: "hard",
    description: "Design the backend pipeline that processes uploaded videos — transcoding, thumbnail generation, and delivery — at a scale of 500 hours of video uploaded per minute.",
    hints: [
      "How do you transcode a 2GB video into multiple resolutions/formats without blocking the uploader?",
      "How do you generate thumbnails at scale?",
      "How do you handle a video that fails transcoding midway?",
    ],
    modelAnswer: "Upload: client chunks video → API server → raw blob to GCS (Google Cloud Storage). Upload complete → publish job to Kafka. Transcoding workers: pool of GPU/CPU workers pull from Kafka, transcode to 360p/480p/720p/1080p/4K using FFmpeg. Store each resolution in GCS. Thumbnail: extract frames at 10% intervals, store in GCS. Failure handling: checkpointing — if transcoder crashes, job requeued from last checkpoint. Idempotent worker design. CDN: YouTube's own CDN (edge caches), popular videos pre-cached globally. Metadata (title, description, tags) in Spanner. Video analytics in BigQuery. For 500 hours/min: ~30,000 parallel transcoding tasks, autoscaling worker fleet.",
  },
  {
    title: "Design Instagram's photo storage",
    company: "Instagram",
    genre: "storage",
    difficulty: "medium",
    description: "Design the photo/video storage and delivery system for Instagram. Users upload 100M photos per day. Each photo must be served in multiple resolutions.",
    hints: [
      "How do you store photos at different resolutions without storing full duplicates?",
      "How do you route users to the nearest copy of a photo?",
      "How do you handle the thundering herd when a celebrity posts?",
    ],
    modelAnswer: "Upload: presigned S3 URL → direct client-to-S3 upload (bypasses app servers). On upload complete: Lambda trigger → resize worker generates 4 sizes (thumbnail 150px, small 320px, medium 640px, original). Store all sizes in S3 under consistent key scheme. CDN (CloudFront) in front of S3 — cache popular photos at edge. Cache-Control headers set to 1 year (photos are immutable). Celebrity post thundering herd: CDN handles naturally with cache warming. Photo metadata (owner, caption, tags, location) in Postgres sharded by user_id. Explore/hashtag search: Elasticsearch. Story content (24h expiry): TTL set on S3 objects + DynamoDB metadata with TTL.",
  },
  {
    title: "Design a payment processing system",
    company: "Stripe",
    genre: "payments",
    difficulty: "hard",
    description: "Design a payment processing platform that handles credit card charges, refunds, and payouts for millions of merchants. The system must be highly reliable, idempotent, and PCI-compliant.",
    hints: [
      "How do you prevent a charge from being processed twice if the client retries?",
      "How do you handle partial failures in a charge→capture→settle flow?",
      "How do you store card data without violating PCI compliance?",
      "What does the data model for payments, refunds, and disputes look like?",
    ],
    modelAnswer: "Idempotency keys: client provides unique key per request → server stores key+result → on retry, return cached result instead of re-processing. Charge flow (3-phase): authorize → capture → settle. Each phase is a separate DB record with status. Saga pattern for compensation on failure. Card data: tokenize at entry point (Stripe.js), raw PANs never touch application servers — stored in separate PCI-scoped vault. Ledger: double-entry accounting in Postgres (every debit has matching credit). Webhook delivery: async, retry with exponential backoff, idempotent handlers. Fraud detection: ML model scores each transaction before authorization. Reconciliation job nightly against card network settlement files.",
  },
  {
    title: "Design Discord's voice channels",
    company: "Discord",
    genre: "distributed-systems",
    difficulty: "hard",
    description: "Design the real-time voice communication system that allows thousands of users to join voice channels simultaneously with low latency audio.",
    hints: [
      "What protocol is best suited for real-time audio? Why not HTTP?",
      "How do you minimize audio latency across geographic regions?",
      "How do you handle users joining/leaving mid-conversation?",
      "What happens when a voice server crashes?",
    ],
    modelAnswer: "WebRTC for client-to-server audio (UDP-based, handles packet loss gracefully). Voice servers (media servers) in each region receive all audio streams, mix, and rebroadcast to all participants. Client connects to nearest voice server via routing service (anycast + latency probe). Selective forwarding unit (SFU) architecture — server doesn't decode/re-encode, just forwards RTP packets to reduce CPU. Signaling via WebSocket (join/leave/mute events). On voice server crash: clients detect via WebSocket disconnect → reconnect to next available server within 2-3 seconds. Capacity: each voice server handles ~1000 concurrent users. Auto-scaling based on active channel count. Jitter buffer on client side for smooth playback.",
  },
  {
    title: "Design TikTok's recommendation engine",
    company: "TikTok",
    genre: "feed",
    difficulty: "hard",
    description: "Design the For You Page recommendation system that serves hyper-personalized short video feeds to 1B users, making TikTok one of the most engaging apps in history.",
    hints: [
      "What signals does TikTok use beyond explicit likes and follows?",
      "How do you bootstrap recommendations for a new user with no history?",
      "How do you balance exploration (new content) vs. exploitation (known preferences)?",
      "How do you handle content moderation at this scale?",
    ],
    modelAnswer: "Two-stage retrieval + ranking. Retrieval: candidate generation from collaborative filtering (users similar to you liked X), content-based filtering (videos similar to ones you've watched), trending pool. Ranking: deep learning model with features: watch time %, replay count, share, comment, sound on, account age, device. Implicit signals weighted heavily — 3 seconds watched > explicit like. Cold start: new users shown trending + geo-popular content, rapidly personalizes after 5-10 interactions. New content: every video gets exposure to a small test audience; performance metrics determine broader distribution (viral loop). Real-time feature store (Redis) for freshness. Batch model training nightly, online learning for trending signals. A/B test ranking changes on 1% traffic before rollout.",
  },
  {
    title: "Design a URL shortener",
    company: null,
    genre: "distributed-systems",
    difficulty: "easy",
    description: "Design a URL shortening service like bit.ly. Users submit a long URL and get a short 7-character code. Redirects must be fast (<10ms). System handles 100M URLs and 10B redirects/month.",
    hints: [
      "How do you generate unique short codes at scale without collisions?",
      "Where is the bottleneck — reads or writes?",
      "How do you make redirects as fast as possible?",
    ],
    modelAnswer: "Encode a base-62 counter (a-z, A-Z, 0-9) for 7 characters → 62^7 ≈ 3.5T unique URLs. Counter maintained in Redis (INCR) or distributed ID generator (Snowflake). Short code → long URL mapping in Cassandra (key-value, read-optimized). Redirect: DNS → load balancer → app server → Redis cache lookup → 301/302 redirect. Cache popular URLs in Redis (LRU, TTL 24h) — 80% of traffic served from cache. Write path: generate code → write to Cassandra → cache. Custom aliases: check availability → store with custom key. Analytics: click events to Kafka → Flink aggregation → analytics DB. CDN at DNS level can cache popular redirects further.",
  },
  {
    title: "Design a rate limiter",
    company: null,
    genre: "distributed-systems",
    difficulty: "easy",
    description: "Design a rate limiting service that restricts clients to N requests per time window. It must work across multiple API server instances with sub-millisecond overhead per request.",
    hints: [
      "How do you implement rate limiting across multiple servers sharing no memory?",
      "What algorithm do you use — fixed window, sliding window, or token bucket?",
      "How do you handle race conditions when multiple requests arrive simultaneously?",
    ],
    modelAnswer: "Redis-based token bucket or sliding window counter. Token bucket: each client key has a counter and last-refill timestamp in Redis. Use Lua script (atomic) to check + decrement in one operation — prevents race conditions. Sliding window log: store each request timestamp in Redis sorted set (ZSET), trim entries older than window on each request, check count. Fixed window: INCR + EXPIRE — simpler but allows 2× burst at window boundaries. Middleware on API gateway (not app servers) to avoid N round-trips. Redis cluster for HA. Rate limit headers returned: X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset. Different limits per endpoint, per user tier (free vs. paid). Distributed: all app servers hit same Redis → consistent limits.",
  },
  {
    title: "Design a distributed cache",
    company: null,
    genre: "distributed-systems",
    difficulty: "medium",
    description: "Design a distributed in-memory cache system like Redis or Memcached. The cache must support GET/SET/DELETE, handle node failures, and scale horizontally to petabytes of data.",
    hints: [
      "How do you distribute keys across multiple cache nodes?",
      "What happens when a cache node goes down?",
      "How do you handle cache invalidation when the underlying data changes?",
      "How do you prevent cache stampede (thundering herd on cache miss)?",
    ],
    modelAnswer: "Consistent hashing ring to distribute keys across nodes — each node owns a range of the ring. Virtual nodes (vNodes) per physical server for even distribution. On node failure: successor node takes over that range (replication to next N nodes for redundancy). Client library handles routing (knows ring topology via gossip protocol). Cache invalidation strategies: TTL (simple, eventual consistency), write-through (update cache on write), write-behind (async). Cache stampede prevention: mutex lock on first miss (one request populates, others wait), or probabilistic early expiration. Eviction policies: LRU for general use, LFU for skewed access patterns. Replication: primary-replica per shard for read scaling. Persistence: periodic snapshots + AOF log for recovery.",
  },
  {
    title: "Design a push notification system",
    company: null,
    genre: "notifications",
    difficulty: "medium",
    description: "Design a push notification system that delivers notifications to iOS and Android devices for a social platform with 500M users. Notifications must be delivered within 5 seconds of the triggering event.",
    hints: [
      "How do you route a notification to the correct device when a user has multiple devices?",
      "How do you handle APNs/FCM rate limits and failures?",
      "How do you avoid sending notifications to users who have disabled them?",
    ],
    modelAnswer: "Device token registry: user_id → [device_token, platform (iOS/Android), enabled] in Cassandra. Notification service consumes events from Kafka (new message, like, follow). Per notification: look up recipient's devices → check preferences → batch by platform → send to APNs (iOS) or FCM (Android). APNs/FCM handle last-mile delivery. Rate limiting: respect platform limits, queue excess with priority. Delivery tracking: APNs/FCM feedback service reports unregistered tokens → clean up registry. User preferences stored in Redis (fast read). Notification aggregation: if 50 likes in 10 min → send one 'and 49 others liked your post'. Failed delivery (device offline): platform stores and delivers when device reconnects (up to 28 days for FCM). Dead letter queue for permanent failures.",
  },
  {
    title: "Design a leaderboard",
    company: null,
    genre: "storage",
    difficulty: "easy",
    description: "Design a real-time leaderboard for a mobile game with 10M active players. The leaderboard shows the top 100 players and a player's own rank. Scores update in real time.",
    hints: [
      "How do you efficiently find a player's rank among 10M players?",
      "How do you handle score updates without recomputing the entire ranking?",
      "What data structure is ideal for sorted rankings with fast updates?",
    ],
    modelAnswer: "Redis sorted set (ZSET) — O(log N) insertion/update, O(log N) rank lookup. ZADD updates score, ZREVRANK returns player's position, ZREVRANGE returns top N. For 10M players, Redis ZSET handles this easily (each entry ~100 bytes → ~1GB total). Score update: ZADD leaderboard <score> <player_id>. Top 100: ZREVRANGE leaderboard 0 99 WITHSCORES. Player rank: ZREVRANK leaderboard <player_id>. Persistence: Postgres as source of truth, Redis as read-through cache. Batch sync Postgres → Redis on startup. Weekly/monthly leaderboards: separate ZSET per time window, expire with TTL. Regional leaderboards: separate ZSET per region. Anti-cheat: validate score updates server-side before accepting.",
  },
];
