export interface SeedQuestion {
  title: string;
  company: string | null;
  genre: string;
  difficulty: string;
  description: string;
  hints: string[];
  modelAnswer: string;
}

export const SEED_QUESTIONS: SeedQuestion[] = [
  {
    title: "Design the Twitter feed",
    company: "Twitter",
    genre: "feed",
    difficulty: "hard",
    description: "Design a system that allows users to post tweets and see a personalized feed of tweets from people they follow. The system must support 300M daily active users, with reads heavily outnumbering writes.",
    hints: [
      "Consider fanout-on-write vs fanout-on-read for feed generation",
      "How do you handle celebrity accounts with millions of followers?",
      "What does the data model for tweets and follow relationships look like?",
      "How would you handle timeline cache invalidation?",
    ],
    modelAnswer: "Use a hybrid fanout approach: fanout-on-write for regular users (push tweets to follower timelines at write time), fanout-on-read for celebrities (pull on demand). Store timelines in Redis sorted sets (tweet IDs by timestamp). Tweets in Cassandra (wide-column, write-optimized). Follow graph in a graph DB or adjacency list in Redis. CDN for media. Load balancers → stateless app servers. Separate read/write paths. Timeline service, tweet service, user service as independent microservices. For 300M DAU: estimate ~100M feed reads/day → Redis cluster with ~1M timeline entries cached per shard.",
  },
  {
    title: "Design Uber's dispatch system",
    company: "Uber",
    genre: "distributed-systems",
    difficulty: "hard",
    description: "Design the backend system that matches riders with nearby drivers in real time. The system must handle 15M trips per day globally, with sub-second matching latency.",
    hints: [
      "How do you efficiently find nearby drivers without querying all drivers?",
      "What happens if the matching service goes down mid-ride?",
      "How do you handle surge pricing decisions?",
      "Consider geospatial indexing strategies.",
    ],
    modelAnswer: "Geospatial index using geohash or S2 cells — drivers report location every 4 seconds to a location service, stored in Redis geospatial index. Matching service queries drivers within expanding radius using GEORADIUS. WebSocket or long-polling for real-time driver updates to rider app. Ride state machine (requested → matching → accepted → in-progress → completed) persisted in Postgres with Redis cache. Kafka for async events (trip completion → billing → ratings). Separate supply/demand forecasting service for surge. Distributed lock (Redis) on driver assignment to prevent double-booking. Fallback: if matching service fails, client retries with exponential backoff.",
  },
  {
    title: "Design Netflix's CDN",
    company: "Netflix",
    genre: "cdn",
    difficulty: "hard",
    description: "Design the content delivery system that streams video to 200M subscribers globally with minimal buffering. Netflix accounts for ~15% of global internet traffic.",
    hints: [
      "How do you decide which content to pre-position at which edge nodes?",
      "What encoding formats and bitrates do you store?",
      "How does the client adapt to changing network conditions?",
      "How do you handle a new popular show that everyone watches at once?",
    ],
    modelAnswer: "Open Connect CDN: Netflix-operated servers at ISP data centers. Pre-position popular content using ML predictions (top 1000 titles cover ~80% of streams). Store multiple encodings (H.264/H.265/AV1) at 7 bitrates (0.5Mbps → 20Mbps). Client uses ABR (adaptive bitrate) — downloads 2-4 second chunks, switches quality based on buffer health and bandwidth estimate. Manifest file served from AWS; actual chunks from nearest Open Connect appliance. For new popular shows: replicate to all edge nodes before launch. CDN miss → origin in AWS S3. ISP peering reduces transit cost. Separate metadata service (title, thumbnails) from video delivery path.",
  },
  {
    title: "Design WhatsApp messaging",
    company: "WhatsApp",
    genre: "messaging",
    difficulty: "medium",
    description: "Design a messaging system that supports 1:1 and group chats, delivery receipts, and end-to-end encryption for 2B users. Messages must be delivered even when recipients are offline.",
    hints: [
      "How do you handle message delivery when the recipient is offline?",
      "What is the data model for group chats with up to 1024 members?",
      "How do delivery receipts (sent/delivered/read) work at scale?",
      "Where do you store message history?",
    ],
    modelAnswer: "Persistent WebSocket connections from clients to chat servers. Message queue (Kafka) for reliable delivery — messages persisted until ACKed. When recipient offline: store in DB, push notification via APNS/FCM, deliver on reconnect. Message store: Cassandra with (chat_id, timestamp) partition key for efficient range queries. E2E encryption: Signal Protocol — keys never on server. Group messages: fan out to each member's queue. Delivery receipts: client sends ACK → server updates status → notifies sender. Media stored in distributed blob store (separate from message store). Chat servers stateless behind load balancer; consistent hashing for WebSocket routing.",
  },
  {
    title: "Design Amazon's product search",
    company: "Amazon",
    genre: "search",
    difficulty: "medium",
    description: "Design a product search system that handles 500M product catalog entries and serves 1B search queries per day with sub-100ms latency. Results must be ranked by relevance and personalized.",
    hints: [
      "How do you index 500M products for full-text search?",
      "What signals go into ranking: relevance, sales, reviews, personalization?",
      "How do you handle search suggestions and spell correction?",
      "How do you update the index when product data changes?",
    ],
    modelAnswer: "Elasticsearch cluster for full-text search — inverted index on title, description, category. Separate ranking service: base score (BM25 relevance) × sales velocity × review score × personalization multiplier. Personalization: user's purchase/click history → feature vector → dot product with item embeddings (ANN index, e.g. FAISS). Query pipeline: spell check (edit distance) → query expansion (synonyms) → retrieval → rerank → filter by availability/price. Index updates: product change events → Kafka → index worker → Elasticsearch. Search suggestions: trie or prefix index in Redis. A/B test ranking changes continuously. Cache popular queries (Redis, TTL 5min).",
  },
  {
    title: "Design Google Docs collaborative editing",
    company: "Google",
    genre: "storage",
    difficulty: "hard",
    description: "Design a real-time collaborative document editor where multiple users can edit the same document simultaneously and see each other's changes instantly.",
    hints: [
      "How do you handle two users editing the same character position simultaneously?",
      "How do you sync state when a user reconnects after being offline?",
      "What is the data model for document content and edit history?",
      "How do you scale to millions of concurrent documents?",
    ],
    modelAnswer: "Operational Transformation (OT) or CRDT for conflict resolution — OT is simpler for server-mediated systems. Each operation (insert/delete at position) transformed against concurrent ops before applying. Server as source of truth: client sends op → server transforms against pending ops → broadcasts transformed op to all collaborators. Document stored as op log (append-only) + periodic snapshots in Bigtable. Presence (cursor positions) via separate lightweight pub/sub (Redis). WebSocket per document session; stateful collaboration server per active document. On reconnect: client sends last known revision → server replays missing ops. Separate read path (view document) from edit path. Autosave every 30s to prevent data loss.",
  },
  {
    title: "Design Airbnb's booking system",
    company: "Airbnb",
    genre: "payments",
    difficulty: "medium",
    description: "Design a booking platform that allows hosts to list properties and guests to search, book, and pay. The system must prevent double-bookings and handle payment processing reliably.",
    hints: [
      "How do you prevent two guests from booking the same property on the same night?",
      "How do you handle partial payment failures?",
      "What is the data model for availability calendars?",
      "How do you handle the search for available properties by date range?",
    ],
    modelAnswer: "Availability stored as date-range records per listing (not one record per day). Search uses availability index (Elasticsearch with date range filter). Booking flow: optimistic lock — reserve availability (status: HOLD with TTL 10min) → process payment → confirm booking atomically. Two-phase: if payment fails, release hold. Idempotency keys on payment API to prevent duplicate charges. Postgres for bookings/payments (ACID). Availability calendar: cache in Redis, invalidated on booking. Host payout via background job after check-in + grace period. Cancellation policy applied at booking service layer. Separate listing service, booking service, payment service — saga pattern for cross-service consistency.",
  },
  {
    title: "Design LinkedIn's news feed",
    company: "LinkedIn",
    genre: "feed",
    difficulty: "medium",
    description: "Design a professional news feed that shows posts from a user's connections and followed companies. Feed must be relevant, real-time, and personalized for 800M users.",
    hints: [
      "How is the LinkedIn feed different from Twitter's in terms of graph structure?",
      "How do you balance recency vs. relevance in ranking?",
      "How do you handle viral content that suddenly gets many engagements?",
    ],
    modelAnswer: "Push-pull hybrid similar to Twitter but with connection graph instead of follow graph. Connection degree matters (1st degree > 2nd degree). Feed generation: fanout-on-write for regular users, fanout-on-read for viral posts. Ranking model: engagement score × recency decay × connection strength × content type preference (ML model). Feed stored in Redis per user. Post engagement (likes, comments, shares) updates ranking score asynchronously via Kafka. Viral detection: if post engagement rate exceeds threshold, switch to pull-based for that post. Notification service for real-time feed updates. Separate professional content signals: job changes, endorsements, articles weighted higher.",
  },
  {
    title: "Design Dropbox file sync",
    company: "Dropbox",
    genre: "storage",
    difficulty: "medium",
    description: "Design a file synchronization service that keeps files in sync across multiple devices for 700M users. Files range from 1KB to 50GB.",
    hints: [
      "How do you efficiently sync only the changed parts of a file?",
      "How do you handle conflicts when the same file is edited on two devices simultaneously?",
      "Where do you store file metadata vs. file content?",
      "How do you handle large file uploads reliably?",
    ],
    modelAnswer: "Split files into 4MB chunks, hash each chunk (SHA-256). On sync: compare chunk hashes, upload only changed chunks (delta sync). Metadata (file path, chunk list, version) in Postgres. Chunks in S3 (content-addressed by hash — deduplication is free). Upload: multipart upload directly to S3 via presigned URLs. Client syncs via long-polling or WebSocket to notification service. Conflict: both versions kept, user prompted to resolve. Version history: immutable chunk store + metadata snapshots. Large file handling: chunked upload with resumable sessions. Bandwidth optimization: compress before upload, LAN sync (detect peers on same network).",
  },
  {
    title: "Design Slack real-time messaging",
    company: "Slack",
    genre: "messaging",
    difficulty: "hard",
    description: "Design a team messaging platform with channels, direct messages, search, and real-time notifications for 20M daily active users across thousands of workspaces.",
    hints: [
      "How do you isolate data between different company workspaces?",
      "How does channel message search work at scale?",
      "How do you deliver real-time messages to users who may be on web, desktop, and mobile?",
    ],
    modelAnswer: "Workspace-level data isolation — each workspace can be sharded independently. Messages stored in Cassandra (workspace_id, channel_id, timestamp). Full-text search via Elasticsearch per workspace index. Real-time delivery: WebSocket gateway (stateful) → client. When user sends message: API server → Kafka → fanout service → pushes to all channel members' WebSocket connections. Members not connected: push notification. Presence service: Redis tracking connected users per workspace. Read state tracking: last-read timestamp per user per channel in Redis. App unfurling (link previews) as async job. Audit logs for enterprise customers. Rate limiting per workspace to prevent noisy neighbors.",
  },
  {
    title: "Design YouTube's video upload pipeline",
    company: "YouTube",
    genre: "cdn",
    difficulty: "hard",
    description: "Design the backend pipeline that processes uploaded videos — transcoding, thumbnail generation, and delivery — at a scale of 500 hours of video uploaded per minute.",
    hints: [
      "How do you transcode a 2GB video into multiple resolutions/formats without blocking the uploader?",
      "How do you generate thumbnails at scale?",
      "How do you handle a video that fails transcoding midway?",
    ],
    modelAnswer: "Upload: client chunks video → API server → raw blob to GCS (Google Cloud Storage). Upload complete → publish job to Kafka. Transcoding workers: pool of GPU/CPU workers pull from Kafka, transcode to 360p/480p/720p/1080p/4K using FFmpeg. Store each resolution in GCS. Thumbnail: extract frames at 10% intervals, store in GCS. Failure handling: checkpointing — if transcoder crashes, job requeued from last checkpoint. Idempotent worker design. CDN: YouTube's own CDN (edge caches), popular videos pre-cached globally. Metadata (title, description, tags) in Spanner. Video analytics in BigQuery. For 500 hours/min: ~30,000 parallel transcoding tasks, autoscaling worker fleet.",
  },
  {
    title: "Design Instagram's photo storage",
    company: "Instagram",
    genre: "storage",
    difficulty: "medium",
    description: "Design the photo/video storage and delivery system for Instagram. Users upload 100M photos per day. Each photo must be served in multiple resolutions.",
    hints: [
      "How do you store photos at different resolutions without storing full duplicates?",
      "How do you route users to the nearest copy of a photo?",
      "How do you handle the thundering herd when a celebrity posts?",
    ],
    modelAnswer: "Upload: presigned S3 URL → direct client-to-S3 upload (bypasses app servers). On upload complete: Lambda trigger → resize worker generates 4 sizes (thumbnail 150px, small 320px, medium 640px, original). Store all sizes in S3 under consistent key scheme. CDN (CloudFront) in front of S3 — cache popular photos at edge. Cache-Control headers set to 1 year (photos are immutable). Celebrity post thundering herd: CDN handles naturally with cache warming. Photo metadata (owner, caption, tags, location) in Postgres sharded by user_id. Explore/hashtag search: Elasticsearch. Story content (24h expiry): TTL set on S3 objects + DynamoDB metadata with TTL.",
  },
  {
    title: "Design a payment processing system",
    company: "Stripe",
    genre: "payments",
    difficulty: "hard",
    description: "Design a payment processing platform that handles credit card charges, refunds, and payouts for millions of merchants. The system must be highly reliable, idempotent, and PCI-compliant.",
    hints: [
      "How do you prevent a charge from being processed twice if the client retries?",
      "How do you handle partial failures in a charge→capture→settle flow?",
      "How do you store card data without violating PCI compliance?",
      "What does the data model for payments, refunds, and disputes look like?",
    ],
    modelAnswer: "Idempotency keys: client provides unique key per request → server stores key+result → on retry, return cached result instead of re-processing. Charge flow (3-phase): authorize → capture → settle. Each phase is a separate DB record with status. Saga pattern for compensation on failure. Card data: tokenize at entry point (Stripe.js), raw PANs never touch application servers — stored in separate PCI-scoped vault. Ledger: double-entry accounting in Postgres (every debit has matching credit). Webhook delivery: async, retry with exponential backoff, idempotent handlers. Fraud detection: ML model scores each transaction before authorization. Reconciliation job nightly against card network settlement files.",
  },
  {
    title: "Design Discord's voice channels",
    company: "Discord",
    genre: "distributed-systems",
    difficulty: "hard",
    description: "Design the real-time voice communication system that allows thousands of users to join voice channels simultaneously with low latency audio.",
    hints: [
      "What protocol is best suited for real-time audio? Why not HTTP?",
      "How do you minimize audio latency across geographic regions?",
      "How do you handle users joining/leaving mid-conversation?",
      "What happens when a voice server crashes?",
    ],
    modelAnswer: "WebRTC for client-to-server audio (UDP-based, handles packet loss gracefully). Voice servers (media servers) in each region receive all audio streams, mix, and rebroadcast to all participants. Client connects to nearest voice server via routing service (anycast + latency probe). Selective forwarding unit (SFU) architecture — server doesn't decode/re-encode, just forwards RTP packets to reduce CPU. Signaling via WebSocket (join/leave/mute events). On voice server crash: clients detect via WebSocket disconnect → reconnect to next available server within 2-3 seconds. Capacity: each voice server handles ~1000 concurrent users. Auto-scaling based on active channel count. Jitter buffer on client side for smooth playback.",
  },
  {
    title: "Design TikTok's recommendation engine",
    company: "TikTok",
    genre: "feed",
    difficulty: "hard",
    description: "Design the For You Page recommendation system that serves hyper-personalized short video feeds to 1B users, making TikTok one of the most engaging apps in history.",
    hints: [
      "What signals does TikTok use beyond explicit likes and follows?",
      "How do you bootstrap recommendations for a new user with no history?",
      "How do you balance exploration (new content) vs. exploitation (known preferences)?",
      "How do you handle content moderation at this scale?",
    ],
    modelAnswer: "Two-stage retrieval + ranking. Retrieval: candidate generation from collaborative filtering (users similar to you liked X), content-based filtering (videos similar to ones you've watched), trending pool. Ranking: deep learning model with features: watch time %, replay count, share, comment, sound on, account age, device. Implicit signals weighted heavily — 3 seconds watched > explicit like. Cold start: new users shown trending + geo-popular content, rapidly personalizes after 5-10 interactions. New content: every video gets exposure to a small test audience; performance metrics determine broader distribution (viral loop). Real-time feature store (Redis) for freshness. Batch model training nightly, online learning for trending signals. A/B test ranking changes on 1% traffic before rollout.",
  },
  {
    title: "Design a URL shortener",
    company: null,
    genre: "distributed-systems",
    difficulty: "easy",
    description: "Design a URL shortening service like bit.ly. Users submit a long URL and get a short 7-character code. Redirects must be fast (<10ms). System handles 100M URLs and 10B redirects/month.",
    hints: [
      "How do you generate unique short codes at scale without collisions?",
      "Where is the bottleneck — reads or writes?",
      "How do you make redirects as fast as possible?",
    ],
    modelAnswer: "Encode a base-62 counter (a-z, A-Z, 0-9) for 7 characters → 62^7 ≈ 3.5T unique URLs. Counter maintained in Redis (INCR) or distributed ID generator (Snowflake). Short code → long URL mapping in Cassandra (key-value, read-optimized). Redirect: DNS → load balancer → app server → Redis cache lookup → 301/302 redirect. Cache popular URLs in Redis (LRU, TTL 24h) — 80% of traffic served from cache. Write path: generate code → write to Cassandra → cache. Custom aliases: check availability → store with custom key. Analytics: click events to Kafka → Flink aggregation → analytics DB. CDN at DNS level can cache popular redirects further.",
  },
  {
    title: "Design a rate limiter",
    company: null,
    genre: "distributed-systems",
    difficulty: "easy",
    description: "Design a rate limiting service that restricts clients to N requests per time window. It must work across multiple API server instances with sub-millisecond overhead per request.",
    hints: [
      "How do you implement rate limiting across multiple servers sharing no memory?",
      "What algorithm do you use — fixed window, sliding window, or token bucket?",
      "How do you handle race conditions when multiple requests arrive simultaneously?",
    ],
    modelAnswer: "Redis-based token bucket or sliding window counter. Token bucket: each client key has a counter and last-refill timestamp in Redis. Use Lua script (atomic) to check + decrement in one operation — prevents race conditions. Sliding window log: store each request timestamp in Redis sorted set (ZSET), trim entries older than window on each request, check count. Fixed window: INCR + EXPIRE — simpler but allows 2× burst at window boundaries. Middleware on API gateway (not app servers) to avoid N round-trips. Redis cluster for HA. Rate limit headers returned: X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset. Different limits per endpoint, per user tier (free vs. paid). Distributed: all app servers hit same Redis → consistent limits.",
  },
  {
    title: "Design a distributed cache",
    company: null,
    genre: "distributed-systems",
    difficulty: "medium",
    description: "Design a distributed in-memory cache system like Redis or Memcached. The cache must support GET/SET/DELETE, handle node failures, and scale horizontally to petabytes of data.",
    hints: [
      "How do you distribute keys across multiple cache nodes?",
      "What happens when a cache node goes down?",
      "How do you handle cache invalidation when the underlying data changes?",
      "How do you prevent cache stampede (thundering herd on cache miss)?",
    ],
    modelAnswer: "Consistent hashing ring to distribute keys across nodes — each node owns a range of the ring. Virtual nodes (vNodes) per physical server for even distribution. On node failure: successor node takes over that range (replication to next N nodes for redundancy). Client library handles routing (knows ring topology via gossip protocol). Cache invalidation strategies: TTL (simple, eventual consistency), write-through (update cache on write), write-behind (async). Cache stampede prevention: mutex lock on first miss (one request populates, others wait), or probabilistic early expiration. Eviction policies: LRU for general use, LFU for skewed access patterns. Replication: primary-replica per shard for read scaling. Persistence: periodic snapshots + AOF log for recovery.",
  },
  {
    title: "Design a push notification system",
    company: null,
    genre: "notifications",
    difficulty: "medium",
    description: "Design a push notification system that delivers notifications to iOS and Android devices for a social platform with 500M users. Notifications must be delivered within 5 seconds of the triggering event.",
    hints: [
      "How do you route a notification to the correct device when a user has multiple devices?",
      "How do you handle APNs/FCM rate limits and failures?",
      "How do you avoid sending notifications to users who have disabled them?",
    ],
    modelAnswer: "Device token registry: user_id → [device_token, platform (iOS/Android), enabled] in Cassandra. Notification service consumes events from Kafka (new message, like, follow). Per notification: look up recipient's devices → check preferences → batch by platform → send to APNs (iOS) or FCM (Android). APNs/FCM handle last-mile delivery. Rate limiting: respect platform limits, queue excess with priority. Delivery tracking: APNs/FCM feedback service reports unregistered tokens → clean up registry. User preferences stored in Redis (fast read). Notification aggregation: if 50 likes in 10 min → send one 'and 49 others liked your post'. Failed delivery (device offline): platform stores and delivers when device reconnects (up to 28 days for FCM). Dead letter queue for permanent failures.",
  },
  {
    title: "Design a leaderboard",
    company: null,
    genre: "storage",
    difficulty: "easy",
    description: "Design a real-time leaderboard for a mobile game with 10M active players. The leaderboard shows the top 100 players and a player's own rank. Scores update in real time.",
    hints: [
      "How do you efficiently find a player's rank among 10M players?",
      "How do you handle score updates without recomputing the entire ranking?",
      "What data structure is ideal for sorted rankings with fast updates?",
    ],
    modelAnswer: "Redis sorted set (ZSET) — O(log N) insertion/update, O(log N) rank lookup. ZADD updates score, ZREVRANK returns player's position, ZREVRANGE returns top N. For 10M players, Redis ZSET handles this easily (each entry ~100 bytes → ~1GB total). Score update: ZADD leaderboard <score> <player_id>. Top 100: ZREVRANGE leaderboard 0 99 WITHSCORES. Player rank: ZREVRANK leaderboard <player_id>. Persistence: Postgres as source of truth, Redis as read-through cache. Batch sync Postgres → Redis on startup. Weekly/monthly leaderboards: separate ZSET per time window, expire with TTL. Regional leaderboards: separate ZSET per region. Anti-cheat: validate score updates server-side before accepting.",
  },

  // --- Questions inspired by awesome-design-md company catalog ---

  {
    title: "Design Spotify's music streaming",
    company: "Spotify",
    genre: "cdn",
    difficulty: "hard",
    description: "Design a music streaming backend that serves 600M users and 100M songs. The system must handle audio playback with <200ms start time, offline sync, and a personalized home feed. Average session is 30 minutes of continuous audio.",
    hints: [
      "How do you store and serve 100M songs efficiently? Where does the audio data live?",
      "How do you deliver audio with low start latency globally?",
      "How do you sync liked songs and playlists across offline devices?",
      "How does Discover Weekly work at a high level — what signals drive recommendations?",
    ],
    modelAnswer: "Audio files stored in GCS/S3 encoded at multiple bitrates (96/160/320 kbps AAC). CDN (Akamai/Fastly) caches popular tracks at edge nodes — top 10% of catalog covers 90% of streams. Prefetch next track while current track is playing to hide latency. Streaming: byte-range HTTP requests for audio segments; client buffers 30 seconds ahead. Offline sync: delta sync — compare local track list against server manifest, download missing encrypted files. Recommendations: collaborative filtering (matrix factorization on play history), audio features (BPM, key, valence extracted via audio ML), NLP on playlist names. Personalization model runs weekly batch (Hadoop/Spark), real-time session signals feed online model. Playlist/library data in Cassandra (user_id partition key). Song metadata in Postgres. Session events (plays, skips, seeks) to Kafka → feature pipeline. Free tier: ad injection between tracks via separate ad-decision service.",
  },
  {
    title: "Design Coinbase's crypto exchange",
    company: "Coinbase",
    genre: "distributed-systems",
    difficulty: "hard",
    description: "Design a cryptocurrency exchange that processes buy/sell orders for BTC, ETH, and hundreds of altcoins for 100M verified users. The order matching engine must be correct, consistent, and capable of 10,000 orders/second per market.",
    hints: [
      "How do you implement an order book that matches buy and sell orders fairly and correctly?",
      "Why is eventual consistency dangerous for financial ledgers — what guarantees do you need?",
      "How do you handle the blockchain settlement layer, which is asynchronous and slow?",
      "How do you protect against double-spend or race conditions in withdrawals?",
    ],
    modelAnswer: "Order matching engine: single-threaded in-memory order book per market (price-time priority). Buy orders (max-heap by price), sell orders (min-heap by price). Matching is deterministic and sequential — no concurrency in the matching core. Orders persisted to Postgres before entering the book (write-ahead). Ledger: double-entry accounting — every trade creates debit+credit entries atomically. ACID Postgres, no eventual consistency for balances. Blockchain settlement: async — on-chain transactions confirmed separately, funds credited after N confirmations (6 for BTC). Deposit watcher service polls blockchain. Withdrawal: two-phase — reserve funds synchronously, broadcast transaction asynchronously, mark settled after confirmation. Hot/cold wallet split: 98% funds in cold storage (offline), hot wallet holds float for withdrawals. Regulatory: KYC/AML checks at onboarding, transaction monitoring for suspicious patterns (ML-based). Rate limiting on order submission per user.",
  },
  {
    title: "Design Notion's block-based editor",
    company: "Notion",
    genre: "storage",
    difficulty: "hard",
    description: "Design the backend for a collaborative workspace where documents are composed of nested blocks (text, headings, tables, databases, embeds). The system must support real-time collaboration, nested pages, and powerful cross-page queries.",
    hints: [
      "How do you model a document made of nested, reorderable blocks in a database?",
      "How do you efficiently move or indent a block that may have hundreds of children?",
      "How does real-time collaboration work without last-write-wins overwriting changes?",
      "How do you implement Notion's 'database' feature where blocks can be queried like a table?",
    ],
    modelAnswer: "Block model: each block is a row in Postgres — (id, parent_id, type, content jsonb, position fractional_index). Fractional indexing for ordering avoids renumbering siblings on move. Nested structure via adjacency list; subtree queries via recursive CTE or materialized path. Real-time collaboration: CRDT (Yjs library) on client, server acts as relay + persistence layer. Each block has a vector clock; concurrent edits to the same block merged by CRDT. Database blocks: each block of type 'database' owns a schema definition; rows are child blocks of type 'page' with properties stored as jsonb. Queries: server-side filter/sort against jsonb properties using Postgres jsonb operators + GIN index. Sharing/permissions: ACL table (block_id, user_id, role) — inheritance from parent via tree traversal. Cross-page links tracked as backlink edges. Full-text search: Elasticsearch synced via Debezium CDC from Postgres. Cache: popular page trees in Redis (cache invalidated via block-level events).",
  },
  {
    title: "Design PostHog's product analytics pipeline",
    company: "PostHog",
    genre: "storage",
    difficulty: "hard",
    description: "Design an analytics pipeline that ingests billions of user events per day, stores them efficiently, and serves queries like 'funnel conversion from signup to purchase' in under 5 seconds for any arbitrary time range.",
    hints: [
      "Why are traditional row-oriented databases bad for analytics workloads?",
      "How do you ingest events at 1M events/second without dropping data?",
      "How do you compute funnels and cohort retention efficiently on billions of rows?",
      "How do you handle late-arriving events and backfills?",
    ],
    modelAnswer: "Ingestion: client sends events → API tier (stateless, auto-scaling) → Kafka (durable buffer, decouples ingestion from storage). Kafka consumers batch-insert into ClickHouse (OLAP column store). ClickHouse table: (team_id, event, timestamp, distinct_id, properties jsonb) with ORDER BY (team_id, toDate(timestamp), event, timestamp) — primary key enables fast range scans. Funnel query: SQL with window functions — MATCH CONDITION on ordered events per distinct_id within session window. ClickHouse handles this natively with its aggregation engine at ~1B rows/sec scan speed. Materialized views for common aggregations (daily active users, event counts by type). Late events: events accepted up to 7 days late; ClickHouse ReplacingMergeTree handles deduplication. Property extraction: event properties are jsonb, extracted to typed columns for hot properties via schema evolution. Multi-tenancy: team_id prefix in all queries, row-level access policies. Retention: hot data in ClickHouse 90 days, older data tiered to S3 (ClickHouse S3 integration).",
  },
  {
    title: "Design Sentry's error tracking platform",
    company: "Sentry",
    genre: "distributed-systems",
    difficulty: "medium",
    description: "Design a system that collects crash reports and exceptions from millions of applications, groups similar errors together ('issue grouping'), and alerts engineers when error rates spike. The system ingests 1B events/day.",
    hints: [
      "How do you group thousands of distinct error instances into a single 'issue' fingerprint?",
      "How do you detect an error rate spike vs. normal traffic fluctuation?",
      "How do you store and query stack traces efficiently?",
      "How do you avoid alert fatigue when a single deploy causes 10,000 new error variants?",
    ],
    modelAnswer: "Ingestion: SDK sends error payload (exception, stack trace, breadcrumbs, tags) to ingest API → Kafka. Consumer pipeline: normalize stack trace (strip line numbers for grouping, apply source maps), compute fingerprint (hash of exception type + top N stack frames after normalization). Fingerprint determines which 'issue' this belongs to — upsert issue table, increment count. Storage: events in Postgres (recent 30 days) with JSONB for variable fields; older events compressed in S3. Issue table: (id, fingerprint, project_id, first_seen, last_seen, count, status). Alert rules: sliding window counter per issue per project — if count increases 10× over baseline in 5 min, trigger alert. Spike detection uses statistical anomaly detection (z-score against last 7 days). Alert deduplication: suppress follow-up alerts for same issue for 1 hour. Source maps: uploaded at deploy time, applied during ingestion to un-minify JS stack traces. Performance monitoring: separate trace table (distributed tracing, span hierarchy) linked to error events by trace_id.",
  },
  {
    title: "Design Linear's issue tracker",
    company: "Linear",
    genre: "storage",
    difficulty: "medium",
    description: "Design a fast, keyboard-driven project management tool where teams manage issues, sprints, and roadmaps. The system must feel instant (<50ms response for all actions) and support real-time sync across team members.",
    hints: [
      "How do you achieve <50ms response times when the database roundtrip alone is 20ms+?",
      "How do you sync issue updates across all team members viewing the same project in real time?",
      "How do you model issues, sub-issues, projects, and cycles (sprints) in a database?",
      "How do you implement optimistic updates in the client without losing data on network failure?",
    ],
    modelAnswer: "Optimistic UI: client applies mutations locally before server confirms — 0ms perceived latency. If server rejects, client rolls back and shows error. Data model: Issue (id, team_id, title, description, status, priority, assignee_id, cycle_id, project_id, parent_issue_id, created_at). Status is a state machine with allowed transitions enforced server-side. Sync: server pushes delta updates via WebSocket to all team members viewing the same workspace. Each mutation broadcasts an event (issue.updated, issue.created) to all connected clients in the workspace. Conflict resolution: last-write-wins for scalar fields (status, assignee), CRDT for description text. API: GraphQL for reads (flexible queries), dedicated mutation endpoints for writes (simpler conflict handling). Full-text search: Postgres pg_trgm for issue title/description search (fast enough for team-scale). Roadmap views: materialized view joins issues → cycles → projects, cached in Redis. Keyboard shortcuts: all actions map to commands processed client-side, API calls batched where possible.",
  },
  {
    title: "Design Vercel's edge deployment platform",
    company: "Vercel",
    genre: "distributed-systems",
    difficulty: "hard",
    description: "Design a platform that deploys frontend applications (Next.js, React) to 100+ edge PoPs worldwide and serves them with cold-start times under 100ms. Each deploy must be atomic, instantly rollbackable, and served from the edge.",
    hints: [
      "How do you propagate a new deployment to 100 edge locations within seconds?",
      "How do you serve serverless functions at the edge with <100ms cold start?",
      "How do you implement atomic deployments (old version serves until new is fully ready)?",
      "How do you handle per-deployment routing so old URLs continue working during rollback?",
    ],
    modelAnswer: "Build pipeline: Git push webhook → build worker pulls code, runs `next build`, produces static assets + function bundles. Assets uploaded to S3 with content-hash filenames (immutable). Deployment record created in DB with unique deployment URL (abc123.vercel.app). Edge propagation: deployment metadata (routing table, function code) replicated to all edge PoPs via a gossip protocol or centralized config push — functions are small JS bundles (<1MB), replication takes 2-5 seconds. Serving: edge PoP matches request to deployment by domain + deployment ID. Static assets served from local cache (warmed from S3 on first request, TTL indefinite due to content hash). Serverless functions: V8 isolates (not containers) — startup time <5ms. Isolate pool kept warm per edge node. Atomic swap: traffic shifted to new deployment only after health check passes on N edge nodes. Rollback: update routing table to point domain back to previous deployment ID — no code movement needed, old bundles already distributed. Custom domains: DNS CNAME → Vercel anycast VIP → edge PoP resolves domain to deployment.",
  },
  {
    title: "Design Figma's real-time design collaboration",
    company: "Figma",
    genre: "distributed-systems",
    difficulty: "hard",
    description: "Design the multiplayer editing backend for a browser-based design tool where dozens of designers can work on the same file simultaneously. Changes must be visible to collaborators within 100ms. Files can contain 10,000+ design objects.",
    hints: [
      "Design tools have a different conflict pattern than text editors — what makes it harder?",
      "How do you handle a user who makes 100 rapid property changes (dragging a slider)?",
      "How do you efficiently sync only the changed parts of a large file to collaborators?",
      "How do you reconstruct a file's state after a collaborator reconnects after 10 minutes offline?",
    ],
    modelAnswer: "Document model: tree of nodes (frames, groups, shapes, text) each with properties (x, y, width, height, fill, etc.). Operations are property-level mutations on node IDs — much more granular than text OT. CRDT for concurrent edits: each property is a Last-Write-Wins register with Lamport timestamp. Dragging: client batches rapid property changes, sends delta at ~20fps (not every pixel move). Server broadcasts deltas to all collaborators via WebSocket. Storage: document as compacted op log in Postgres + S3 snapshot every N ops. Reconnect: client sends last known sequence number → server replays missing ops since then (or sends full snapshot if diff is too large). Multiplayer cursor/selection: low-priority channel, 60ms sync interval, ephemeral (not persisted). File version history: periodic snapshots + op log enables rewind to any point. Access control: real-time permission check on each operation (view-only vs. edit). Thumbnail generation: headless rendering worker generates PNG on save, stores in S3.",
  },
  {
    title: "Design Revolut's neobank ledger",
    company: "Revolut",
    genre: "payments",
    difficulty: "hard",
    description: "Design the core financial ledger for a digital bank serving 40M customers. The system must handle FX conversions, multi-currency accounts, and millions of transactions per day with zero tolerance for lost or duplicated money.",
    hints: [
      "Why is eventual consistency unacceptable for account balances?",
      "How do you implement FX conversion atomically — what happens if the FX rate changes between quote and execution?",
      "How do you ensure a transaction that partially succeeded (e.g., debit happened, credit didn't) is safely recovered?",
      "How do you scale a single-shard ledger database that must be strongly consistent?",
    ],
    modelAnswer: "Ledger model: double-entry accounting — every transaction creates paired entries (debit account A, credit account B). Balance = sum of all entries for an account. Never update balances in-place; always append entries. Strong consistency: Spanner or CockroachDB (globally distributed, serializable isolation). Account balance read: SELECT SUM(amount) — or maintain a running balance with optimistic locking and reconcile nightly. FX conversion: rate locked at quote time (15-second validity), stored in quote table with expiry. Execution: atomic multi-step saga — (1) lock funds, (2) execute FX at locked rate, (3) credit target currency, (4) release lock. If step 2-3 fails, compensating transaction reverses step 1. Idempotency: each transaction has client-provided idempotency key; duplicate requests return cached result. Saga orchestrator persists state so recovery resumes after crash. Compliance: immutable audit log, regulatory reporting via separate read replica. Card payments: separate authorization table (pre-auth holds) — capture releases hold and creates ledger entry. Fraud: ML scoring before authorization, configurable velocity checks per user.",
  },
  {
    title: "Design HashiCorp Vault's secrets management",
    company: "HashiCorp",
    genre: "distributed-systems",
    difficulty: "hard",
    description: "Design a secrets management system that stores API keys, database passwords, and TLS certificates for thousands of services. The system must encrypt all secrets at rest, support automatic secret rotation, and provide fine-grained access control with audit logs.",
    hints: [
      "How do you encrypt secrets in a way that survives database compromise?",
      "How do you bootstrap trust — how does a freshly started application prove its identity to get secrets?",
      "How do you implement dynamic secrets (credentials generated on-demand, expired automatically)?",
      "How do you handle the split-knowledge problem — who holds the master decryption key?",
    ],
    modelAnswer: "Encryption: secrets encrypted with AES-256-GCM using a data encryption key (DEK). DEK itself encrypted with a key encryption key (KEK) stored in HSM or cloud KMS — envelope encryption. At-rest: only encrypted blobs in storage (Consul, Postgres, or Raft). Unseal: on startup, Vault is sealed (can't decrypt). Unseal requires K-of-N shamir secret shares (e.g., 3 of 5 operators each hold one share). Once unsealed, KEK is in memory only. Auth: AppRole (application gets role_id at deploy time, secret_id injected at runtime), Kubernetes auth (pod's JWT verified against k8s API), AWS IAM auth. Fine-grained policies: HCL policy files map paths to capabilities (read/write/delete). Dynamic secrets: for DB credentials, Vault creates a temporary Postgres user on request, returns credentials with TTL (e.g., 1 hour). On TTL expiry, Vault revokes the credentials. Lease system: every secret has a lease; client must renew or secret expires. Audit log: every request logged (requester, path, timestamp) to separate append-only storage. HA: Raft consensus cluster, one active node, automatic failover.",
  },
  {
    title: "Design Pinterest's visual search",
    company: "Pinterest",
    genre: "search",
    difficulty: "hard",
    description: "Design a visual search system that takes an image input and finds visually similar images from a corpus of 300 billion pins. Results must be returned in under 500ms.",
    hints: [
      "How do you represent an image as something you can compare for similarity?",
      "How do you search 300B image vectors without doing a brute-force comparison?",
      "How do you handle the multi-modal case — searching by image AND text ('blue dress like this')?",
      "How do you keep the image index fresh as new pins are uploaded constantly?",
    ],
    modelAnswer: "Image embedding: deep CNN (ResNet/ViT fine-tuned on Pinterest data) encodes each image to a 256-d float vector. Similar images → similar vectors (cosine similarity). Approximate nearest neighbor (ANN) search: FAISS or ScaNN index of 300B vectors — exact search is O(N), ANN reduces to O(log N) using HNSW or IVF. Index sharded across many machines; query fan-out to all shards, merge top-K results. Multi-modal search: encode text query to same embedding space (CLIP model), combine image vector + text vector with learned weights. Image upload pipeline: image → CDN → embedding worker (GPU fleet) → Kafka → index update. Real-time index updates: new pin embeddings appended to index segment; nightly merge rebuilds for compaction. Re-ranking: initial ANN retrieves top-500, ranking model re-scores using engagement signals (similar pins people saved together), diversity injection (avoid 500 identical images). Results served with <200ms p99 by keeping ANN index in memory across shard servers. A/B testing framework evaluates embedding model quality via CTR and save rate.",
  },
  {
    title: "Design Supabase's real-time database subscriptions",
    company: "Supabase",
    genre: "distributed-systems",
    difficulty: "medium",
    description: "Design a system that allows web clients to subscribe to database changes in real time — receiving inserts, updates, and deletes from a Postgres database within milliseconds, with row-level security enforced on the subscription.",
    hints: [
      "How do you detect changes in Postgres and stream them to thousands of connected clients?",
      "How do you enforce row-level security — ensuring a client only receives rows they're allowed to see?",
      "How do you fan out a single database change to 10,000 subscribed clients efficiently?",
      "How do you handle clients reconnecting after a brief network drop without missing events?",
    ],
    modelAnswer: "Change detection: Postgres logical replication with a replication slot. WAL (write-ahead log) decoded by a replication consumer (Supabase Realtime server using wal2json). Every committed INSERT/UPDATE/DELETE row appears as a JSON event on the replication stream. Client subscriptions: clients connect via WebSocket to Realtime server, send subscription filter (table, event type, filter expression). Fan-out: Realtime server maintains in-memory topic map (table → [client connections]). On WAL event, filter matching clients, check RLS. RLS enforcement: for each matching client, evaluate their auth JWT against the row data using Postgres RLS policies — run a lightweight check query per row per subscribed user (or cache policy evaluation). Presence: separate pub/sub channel for ephemeral state (who's online), not tied to WAL. Reconnect: Realtime sends a SYSTEM broadcast with current server timestamp; client uses this as cursor. Events buffered in Redis for 30 seconds — on reconnect, client requests missed events since last cursor. Scaling: multiple Realtime nodes, each consuming the replication stream; consistent hash routes client connections to one node, which handles fan-out for its clients.",
  },
  {
    title: "Design a ClickHouse-based time-series analytics system",
    company: "ClickHouse",
    genre: "storage",
    difficulty: "medium",
    description: "Design a time-series analytics backend that ingests 1M metrics/second from IoT sensors and serves dashboard queries like 'average CPU usage per host over the last 7 days, grouped by 5-minute buckets' in under 2 seconds.",
    hints: [
      "Why is ClickHouse better suited for this than Postgres or MongoDB?",
      "How do you ingest 1M events/second without overwhelming the database with small inserts?",
      "How does ClickHouse's MergeTree engine achieve fast range scans on time-series data?",
      "How do you reduce query latency for common dashboard queries?",
    ],
    modelAnswer: "ClickHouse chosen for columnar storage (reads only needed columns), vectorized query execution, and excellent compression on repeated values. Table: (host_id, metric_name, timestamp, value) with ENGINE = MergeTree() ORDER BY (host_id, metric_name, timestamp). ORDER BY defines the primary index — queries filtering by host_id + time range skip irrelevant data via sparse index. Partition by month for efficient data retention (DROP PARTITION instead of DELETE). Ingestion: producers → Kafka → ClickHouse Kafka table engine (native Kafka consumer) → Materialized View writes to main table. Kafka buffers spikes; ClickHouse inserts in large batches (100K rows) — small inserts create too many part files. Compression: LZ4 on value column (fast), ZSTD on string columns (compact). Materialized views for common aggregations: CREATE MATERIALIZED VIEW mv_5min ... SELECT host_id, toStartOfFiveMinute(timestamp) AS bucket, avg(value) — updates incrementally on insert. Dashboard queries hit materialized view instead of raw table: 100× faster. TTL for retention: ALTER TABLE ... MODIFY TTL timestamp + INTERVAL 90 DAY. Replication: ReplicatedMergeTree across 3 nodes for HA.",
  },
  {
    title: "Design Warp's AI terminal",
    company: "Warp",
    genre: "distributed-systems",
    difficulty: "medium",
    description: "Design a terminal application with an AI assistant feature that can explain commands, suggest fixes for errors, and generate shell scripts from natural language. The AI features must work with low latency and respect user privacy.",
    hints: [
      "What context does the AI need to give useful suggestions — and what data should NOT be sent to a server?",
      "How do you stream AI responses to the terminal UI with low perceived latency?",
      "How do you cache AI responses to avoid redundant API calls for common queries?",
      "How do you handle the case where the user's shell session has context (previous commands, directory) that affects the answer?",
    ],
    modelAnswer: "Context collection: capture the current command, exit code, stderr output (last 2KB), current directory, and shell type — this is the minimum needed for useful suggestions. PII filtering: before sending to AI API, scrub tokens that look like API keys, passwords (regex patterns), or personal paths. User opt-in for sending context. Streaming: AI API supports SSE (server-sent events) or streaming response. Terminal UI renders tokens as they arrive — perceived latency is time-to-first-token (~300ms) not total response time. Context window management: include last 5 commands + outputs in the prompt, but truncate at ~2K tokens to stay fast and cheap. Local caching: hash of (command + context) → cached response, TTL 1 hour. Common queries like 'explain ls -la' or 'fix permission denied error' are highly cacheable. Command-specific suggestions indexed locally (a small FAISS or prefix-tree on known error patterns) for offline first-pass before hitting API. Privacy mode: fully local inference using a small GGUF model (LLaMA 3.2B) via llama.cpp — slower but zero data leaves the machine. Background pre-warming: predict likely next command based on history, pre-fetch AI suggestion speculatively.",
  },
];
